### ISSUE TITLE
footterを最新のものに置き換える

### ISSUE THREAD

**Issue by ayuki-joto** [codeforjapan/Gussuri#42]
全ページ共有で表示、常にページの下部に表示するように
![image](https://user-images.githubusercontent.com/19406594/227696823-b690558c-6c18-44ae-8263-316dd7860768.png)

**Comment by kur00** [comment]
icon 
https://api.flutter.dev/flutter/material/Icons-class.html

**Comment by ayuki-joto** [comment]
![image](https://user-images.githubusercontent.com/19406594/235350386-0eb77305-7c8c-491f-b687-3d7e13e57c22.png)
デザイン更新
