### ISSUE TITLE
背景グラデーションの対応

### ISSUE THREAD

**Issue by kur00** [codeforjapan/Gussuri#55]
背景グラデーションの対応。共通にしちゃってよさそう。
figma: https://www.figma.com/file/MOG4wGFmCGoFq6gYEtcj08/design?node-id=1951-12590&t=Ba0yWcreSLhG82Aw-4

![Screenshot 2023-04-05 at 12 48 05](https://user-images.githubusercontent.com/26044110/229976385-b20e0231-89af-4777-9d32-6a8be07fcfac.png)

**Comment by ayuki-joto** [comment]
body: Container(
        decoration: const BoxDecoration(
            gradient: LinearGradient(
                colors: [
                  Color(0xffffefc7),
                  Color(0xffa4e9ff),
                  Color(0xff6cb9ff),
                  Color(0xff180077),
                  Color(0xff001637),
        ],
              begin: Alignment.topCenter,
              end: Alignment.bottomCenter
            )
        ),
)
これでできそう
