### ISSUE TITLE
カレンダー画面の表示不具合

### ISSUE THREAD

**Issue by forestgtree** [codeforjapan/Gussuri#96]
カレンダー画面を表示した際の不具合についてです。

### 検証環境
- iPhone 14
- iOS 17.2.1
- 2024.1.26 検証

### 操作手順
- 「ホーム」画面から「睡眠記録」をタップして入力
- 入力後、タブバーから「睡眠記録カレンダー」画面に遷移

### 不具合結果
- 曜日のテキストの下側が欠けている（オレンジ囲い）
- 前月の日付と、次月の日付の表示位置が当月日付の位置と揃っていないことと、2023年12月の表示は11月の日付がダブって表示されてしまっている（緑囲い）
- 入力した結果が反映されていない。（1/26にキャラクターの顔が反映されていない）
<img width="1264" alt="image 161" src="https://github.com/codeforjapan/Gussuri/assets/55567929/3cb9086d-ee0d-425d-a1af-3b2839306790">

**Comment by kur00** [comment]
#76 前月の日付と、次月の日付の表示位置が当月日付の位置と揃っていないことと、2023年12月の表示は11月の日付がダブって表示されてしまっている（緑囲い）
#96 入力した結果が反映されていない。（1/26にキャラクターの顔が反映されていない）

**Comment by kur00** [comment]
`曜日のテキストの下側が欠けている（オレンジ囲い）`

だけこのissueで対応
